# Generated by Django 3.0.5 on 2020-04-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20200423_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(max_length=65),
        ),
    ]
